### PR TITLE
Draft v2.0 of ambassador program description

### PR DESCRIPTION
**Pull request by semioticrobotic**
I'm proposing the following changes to the Open Organization Ambassador program description.

A bit of background:

We (@jhibbets and I) drafted v1.0 of the document when our community consisted of precisely zero ambassadors. Since the program has grown, evolved, and flourished, the ambassadors that _have_ joined have shown us the community's true potential. Consequently, I was able to draft new, more concrete language articulating a vision for group.

The most significant change to the program involves the introduction of "participation tiers." In its current iteration, the program simply features a single category of participant: the ambassador. But we've heard from others a desire to engage with the group in ways that do not necessarily (initially, anyway) carry all the weight of ambassador-level responsibilities.

So I've tried to image here a tiered system of participation that match levels of investment with variable expectations and benefits.

Please do read the proposed language and let me know how it strikes you.

### CODE REVIEW

**Comment by RonMcFarland** [comment]
Regarding "Supporters", "Contributors" and "Ambassadors", these categories could be further defined as "technical" and "managerial" as well.  Technology is playing a role in the open organization and requires supporters to move it forward.  Technical supports will play a role.  Also, there is managerial resistance to open organization management principles.  Therefore, open organization managerial support is needed.  This is to be discussed and decided.

**Comment by RonMcFarland** [comment]
A measuring system (multiple-choice questionnaire) for determining which category would be most appropriate (definitely appropriate, developmentally appropriate, not appropriate).  Some people will surely be appropriate for membership, some need some open organization explanation first before membership, others will surely not be appropriate [our CAVE people]).

**Comment by RonMcFarland** [comment]
One membership categories and activities are decided, an explanation of the benefits of becoming a "Supporter", "Contributor" or "Ambassador" decided.  It could be networking, learning, philanthropic, points, prizes or financial.  All of the categories will require a person's effort, time and possibly funds.  Therefore, how and if these three will be covered should be decided.  For example, an "invitation" to an event will require all three (effort, time and money).  Will those expenses be covered is some form?  Is it budgeted for somewhere (for hotels, travel, meals, etc)?  I think that should be decided on and clarified .

**Review by LauraHilliger — COMMENTED** [review]
I <3 the updates from an informational perspective, but I wonder if we might work in a little community character? E.g. we, as a group of people, are pretty weird and fun. How can we put a teaser of that into the description? I feel like it needs a little pizazz*. 

I know that's not specific. Maybe a sentence about history and reasoning for modifying the description? Or using "we" as in "Our community cuts through the BS and translate community specific..."? Or quick examples of *how* we're spreading the principles? 

@whit537 can I fork a PR? I'd love to take a pass on the NEW desc...

*I spelled this correctly on the first try!

**Comment by semioticrobotic** [comment]
I always welcome more pizazz, @LauraHilliger!  And I do agree that the language could be much more plain and direct. I also like the suggestion of adopting the first-person plural. Let me take another look and see what I can do there. Yes—would very much like to hear @whit537's suggestions for collaborating on the new language. My guess would be: Fork [my personal repo](https://github.com/semioticrobotic/ambassador-program-description) containing the new version?

**Comment by chadwhitacre** [comment]
Love seeing the activity here! @RonMcFarland is on fire! 🔥 💃

@LauraHilliger You can definitely make a PR against a PR, though that is some advanced GitHubbing right there. ;-) I believe @semioticrobotic is correct, that you would do that by forking his repo and making a PR. You should be able to give it a shot in-browser [using the GitHub web UI](https://github.com/semioticrobotic/ambassador-program-description/edit/master/ambassador-program-description.md) unless your changes are really major.

In general smaller PRs are easier for everyone to digest than larger.

**Comment by semioticrobotic** [comment]
Alright, @LauraHilliger! See the commit above (or [here](https://github.com/open-organization-ambassadors/ambassador-program-description/pull/1/commits/4b79abfaf578d348697027abda9358685cc128c7)) for my first pass at new language, style, and basic organization.

I'm still mulling over the best way to address @RonMcFarland's comments but haven't forgotten about them!

**Comment by chadwhitacre** [comment]
> suggestions for collaborating on the new language

Another possibility is to use a shared branch in the main repo here, rather than creating a fork. That way all of the ambassadors could add commits to the same branch, which would greatly streamline the collaboration process compared to PRs against PRs (aka "[PR inception](http://blog.balancedpayments.com/pull-request-inception/)" ;).

**Comment by chadwhitacre** [comment]
Like, I just failed to succeed to make a PR against your fork to fix the link syntax error in the last paragraph under [Selection/Candidacy](https://github.com/semioticrobotic/ambassador-program-description/blob/4b79abfaf578d348697027abda9358685cc128c7/ambassador-program-description.md#selectioncandidacy), for example. ;-)

**Comment by semioticrobotic** [comment]
I'm working on addressing @RonMcFarland's comments now. While I'm inclined to think that introducing distinctions in the tiers (e.g., technical/managerial) might add some unnecessary complexity, I _do_ believe that Ron's comment pushes us to include some language in a new section of the document that specifically invites participants with diverse work/industry/technical backgrounds.

**Comment by samuelknuth** [comment]
Love it, and really like the changes in language in the most recent version. My thoughts are around participation. The "invite only" thing doesn't sit too well with me. I think it would be good to express an openness to interested people to reach out in some way. If we only go by invite/nomination we're going to be quite insular.

**Comment by LauraHilliger** [comment]
it's looking great, really happy with the "We"ness of it. 

Re: @samuelknuth comment, maybe just move the sentence "To discuss participation in any capacity, just contact the Opensource.com staff or the open organization ambassadors." to the top and say something like "And of course, current community members are invited to bring others to the party"

On the inviting people with diverse backgrounds – perhaps that's a blurb for the new "Our Ambassadors" page? By way of introduction, "Our Ambassadors have a variety of skills and come from various industries. What they all have in common, however, is a deep love and belief in open practices. Our Ambassadors are..."

**Comment by semioticrobotic** [comment]
Many thanks to @samuelknuth and @LauraHilliger for the re-read and responses. I agree whole-heartedly and will get to work on another revision right away. I also like @LauraHilliger's suggestion to preface the current ambassador "lineup" page with some of the text here. When all this is final, we can certainly do that.

**Comment by semioticrobotic** [comment]
This is really looking great, folks. Thanks for the feedback. My goal is to firm this up and have the new language in place by next week. Does anyone else have questions, comments, reservations, or the like?

**Comment by semioticrobotic** [comment]
Hearing no objections, I'm going to (attempt to) merge our collective revisions and prepare the new document. Thanks, everyone, for your stellar input.

**Comment by RonMcFarland** [comment]
Bryan,

I think you meant "tiered" in your explanation, not "tired".  Jokingly, I
don't think it is tired at all and very alive.

Ron

**Comment by semioticrobotic** [comment]
Ha! You're absolutely right, @RonMcFarland. Great catch. I've fixed it. Thanks for all your great input.

**Pull request merged**
