### PR TITLE
Add an emeritus level

### PR DESCRIPTION
**Pull request by funnelfiasco**
Initial draft of adding an emeritus level, as discussed at All Things Open.

### CODE REVIEW

**Comment by semioticrobotic** [comment]
I think this works really well, @funnelfiasco. It's clear, concise, and inclusive. Wondering what @jenkelchner [thinks of it](https://github.com/open-organization-ambassadors/ambassador-program-description/pull/4/files), as she was also part of the in-person conversation at All Things Open. Feedback welcome from all, of course!

Also wondering: Would we confer emeritus status retroactively—for example, to folks who have already completed their terms as ambassadors? I'm inclined to say "yes," but am open to hearing other points of view.

**Comment by jenkelchner** [comment]
Thanks, @funnelfiasco for the work into this! Generally, it nails it.  My only hesitation is "invite to monthly meetings". I realize that those who have rolled off have done so _more often than not_ because of their responsibilities to other things and time doesn't allow for engagement. 

My hesitation is mainly around the fact we who are present don't have enough time to share and dig into actual Ambassador work as it is. And we only have about 25-40% of us online during said meeting.  Perhaps this is just a different issue to discuss.

Could we not up the 'specialness' of this by making one of the meetings per quarter Emeritus Invited for quarterly reunions?  Maybe this would also help them in making the time to come and participate without it feeling like .... "oh, I'll try next month". ???  

Thoughts @semioticrobotic and @funnelfiasco .. and I haven't had coffee yet so....

**Comment by funnelfiasco** [comment]
I share your concern @jenkelchner. I left it in for two reasons:

1. In practice, I don't see it being an issue. Folks who are too busy or disinterested to be active ambassadors probably won't be crashing the meeting on a regular basis
2. I couldn't think of a way to concisely-but-politely say "Bryan might invite them to the meeting sometimes if there's a reason to"

One solution is to just set the expectation that they can join in listen-only mode. Another is to just drop it with the understanding that Bryan (or an active ambassador) can invite people to participate as appropriate (e.g. if we're talking about a topic that an emeritus is the expert on)

**Comment by funnelfiasco** [comment]
> Perhaps this is just a different issue to discuss.

This too. We need to do something to make our meetings more efficient, but that's a separate topic. I'll start a thread on Discourse

**Comment by jenkelchner** [comment]
Thanks for the extra thoughts @funnelfiasco.  Your right and therefore I now fully agree. :)

**Comment by semioticrobotic** [comment]
Great conversation and thinking here. Thanks @jenkelchner and @funnelfiasco. What if we altered the language a bit to say something like:

>  * A standing invitation to any online ambassador meetings and in-person ambassador meetings they might like to attend.

This way, it reads more like "We're not going to put something on your calendar every month, but the door is always open and you can join us any time."

In other words, "standing invitation" is something like "open invitation," with the understanding that they'll be participating in and contributing to the business of the day (not necessarily usurping time).

**Comment by semioticrobotic** [comment]
I think this is looking great, @funnelfiasco, so I'm going to merge.

One note: For the moment, I removed the benefit of "special designation as an Ambassador Emeritus on Opensource.com," only because that will require some development before we can implement. If we're going to offer it (and we certainly can), I want to be able to actually do so if it's listed in the charter. Will work on it.

**Pull request merged**
